### ISSUE TITLE
导入插件报错

### ISSUE THREAD

**Issue by ruisika** [NewBeginning6/Subdir-vul-find#3]
当我导入插件时出现下面错误
java环境是17 burp版本2022.8.3
java.lang.ClassNotFoundException: burp.BurpExtender 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 	at java.base/java.lang.Class.forName0(Native Method) 	at java.base/java.lang.Class.forName(Class.java:467) 	at burp.no1.g(Unknown Source) 	at burp.no1.<init>(Unknown Source) 	at burp.hh_.V(Unknown Source) 	at burp.nac.lambda$panelLoaded$0(Unknown Source) 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by NewBeginning6** [comment]
独立程序，非burp插件

**Comment by ruisika** [comment]
好的感谢
